### ISSUE TITLE
Bower cannot find package

### ISSUE THREAD

**Issue by bpatra** [OfficeDev/office-ui-fabric-js#122]
Following instructions provided [here](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/PACKAGES.md)
I ran the command 
`bower.cmd install office-ui-fabric-js --save`
and the package cannot be found
`ENOTFOUND Package office-ui-fabric-js not found`

Same thing online with search package [https://bower.io/search/](https://bower.io/search/)

**Comment by Jahnp** [comment]
Thanks for reporting this, @bpatra. It looks like the new Bower package was not registered or published when splitting Office UI Fabric JS off from Core. I've published both new packages to Bower, but since JS was split directly from the old Fabric repo, the tags & release from that project (e.g. 2.6.1) carry over:

![image](https://cloud.githubusercontent.com/assets/307118/18796475/4598ca2e-817e-11e6-8b50-a56853285bb7.png)

We'll get this resolved asap. In the meantime, you can run `bower i office-ui-fabric-js#v1.1.0` with the version set explicitly to get the latest.

**Comment by Jahnp** [comment]
We've removed the old releases, so you should now be able to do a clean `bower install office-ui-fabric-js` now.

**Comment by bpatra** [comment]
I still have troubles `bower office-ui-fabric-js` fetches old version 2.6.1 (note that I removed bower cache)
![bower](https://cloud.githubusercontent.com/assets/2801702/19189997/3833c5d2-8c9b-11e6-8ba9-e077fa2b8596.jpg)

**Comment by renil** [comment]
I have tried both `bower i office-ui-fabric-js#v1.1.0` and `bower i office-ui-fabric-js` after removing bower cache. I am still getting jquery.fabric.js.

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
